### ISSUE TITLE
Сгенерировать нижнее поле

### ISSUE THREAD

**Issue by dgrdn** [dgrdn/MineSweeper#1]
Сгенерировать нижнее игровое поле с задаными размерами.

Под сгенерировать подразумевается создать переменную, которая будет хранить матрицу нашего поля.
Данное поле будет нижним, так как у пользователя не будет возможности видеть это поле. В последующем оно будет использовано для хранения мин и др.

**Comment by chub16** [comment]
добавил bottom_field.py
Логика: получаем от пользователя переменные х - длина у - высота, создаем строку нужной длины а потом умножаем строку на полученную от пользователя высоту
На выходе имеем массив с массивами(матрицу) заданных пользователем размеров с нулями (0 значение по дефолту)

**Comment by chub16** [comment]
добавил bottom_field.py
Логика: получаем от пользователя переменные х - длина у - высота, создаем строку нужной длины а потом умножаем строку на полученную от пользователя высоту
На выходе имеем массив с массивами(матрицу) заданных пользователем размеров с нулями (0 значение по дефолту)
