### ISSUE TITLE
Сгенерировать верхнее поле

### ISSUE THREAD

**Issue by dgrdn** [dgrdn/MineSweeper#2]
Сгенерировать верхнее игровое поле с задаными размерами.

Под сгенерировать подразумевается создать переменную, которая будет хранить матрицу нашего поля.

Данное поле будет верхним, так как пользователь будет видеть данное поле. В последующем оно будет хранить открытые ячейки(информацию о количестве мин вокруг данной ячейки, а также метки мин).

**Comment by chub16** [comment]
Создаем переменную строки с минимально возможным размером и множим на длину
Создаем верхнее поле умножением строк на их количество
Проверки на существование поля здесь не писал, поскольку она проводится при создании нижнего поля.
