### ISSUE TITLE
Сгенерировать мины

### ISSUE THREAD

**Issue by dgrdn** [dgrdn/MineSweeper#3]
Написать фрагмент кода для расстановки определенного числа мин в пределах нижнего игрового поля.

**Comment by chub16** [comment]
Сначала проводим проверку можем ли мы вместить все мины на поле, потом получаем случайную координату ячейки. В цикле проверяем нет ли там уже мины, если мина есть ничего не делаем, если нет то минируем ячейку и увеличиваем итератор на 1. Цикл продолжается пока итератор < количества мин.
